### ISSUE TITLE
mapView Pull Over By tableView

### ISSUE THREAD

**Issue by jassimkm** [iaagg/AGPullView#1]
Hi ,
Can you help me to pull a tableview over mapview using AGPullView . I am using storyboard and swift
Thanks and regards

**Comment by iaagg** [comment]
Sorry that it took me so long to answer to your question.

I decided to add one more example UIViewController written in SWIFT 3.0 to repository. So you can just clone or download example project and look how AGPullView was added in SWIFT.
And I've also modified README file with examples of usage AGPullView with SWIFT.

So you just need to create bridging header in your project and import AGPullViewConfigurer.h there. 
After that it will become available in SWIFT files. Apple has a [documentetion for this](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)
Ones more - look at README for some code snippets written in SWIFT.
