### ISSUE TITLE
Swift 2 example working on Xcode 7

### ISSUE THREAD

**Issue by kishykumar** [iaagg/AGPullView#2]
Hi, 

The current swift example doesn't run on Xcode 7 because the storyboard file doesn't open (except in Xcode 8). 

Can you please provide an example that works in Xcode 7 and Swift 2? 
The swift code gave compilation errors for Swift 2.2 that I was able to resolve. But, storyboard can't be opened. :(

**Comment by iaagg** [comment]
Xcode 7.* support added: https://github.com/iaagg/AGPullView/commit/d404980db5ac0f7a3427ba1d3f351cf31e575875
