### ISSUE TITLE
Show 50% of the AGPullView

### ISSUE THREAD

**Issue by nicoaureliovillanueva** [iaagg/AGPullView#3]
WHOA! Nice work @iaagg!!

I just wanna ask a question? How to show 50% of the AGPullView in first load of the viewcontroller?

Thanks!!!

**Comment by iaagg** [comment]
Hi, @nicoaureliovillanueva! 
I really appreciate the fact that you like it!

To make what you want, you can simply do something like this in your viewWillAppear method:

```
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        self.configurator.percentOfFilling = @50;
        [self.configurator showAnimated:NO];
    });
    
    self.configurator.percentOfFilling = @100;
}
```

It will present your controller with already pulled view for only 50% and only once.

Feel free to ask me more questions or to suggest some new features for AGPullView!

**Comment by iaagg** [comment]
@nicoaureliovillanueva I've just updated AGPullView to version *0.5.0* with new method:

```
- (void)showAnimated:(BOOL)animated forPercent:(NSInteger)percent;
```

You can use it to programmatically pull your view partly in runtime!

**Comment by nicoaureliovillanueva** [comment]
Its working thanks alot @iaagg you saved me! Thanksssss!

**Comment by iaagg** [comment]
@nicoaureliovillanueva, you are welcome!)

**Comment by nicoaureliovillanueva** [comment]
Hi @iaagg on more thing? is it possible if the pully has 3  percentOfFilling?

Like 100%, 50%, and 0%?? Thanks in advance @iaagg

**Comment by iaagg** [comment]
unfortunately, the minimum height for pulled view (which is equal to 0%) was hardcoded, cause I didn't need to hide it fully, or, for instance, to show it just a little. 
If I understood you right, you want to have a possibility to pull it just for several points?
I am going to add this functionality in future, or you can create a pull request if you want to)) I think it will take me one or two weeks, because I don't have time right now for that(

**Comment by nicoaureliovillanueva** [comment]
Hi @iaagg i understand you quite busy.. But can you tell where can i adjust the default Hide percentage? i will adjust to 50% so that the default value is 50% and max is 100%
